### ISSUE TITLE
Add popup warning about data leaving the client

### ISSUE THREAD

**Issue by fedorov** [faustomilletari/TOMAAT-Slicer#2]
Thinking more about this extension, and after trying it out, I think it would be appropriate (if not mandatory) to have a very prominent warning for the user that the data to be segmented is going to leave the computer.

The approach taken in this extension is highly unconventional to Slicer development model, which usually is to do all analysis locally. Considering the sensitive nature of the image data and regulations, I recommend that for every click of "Segment" button you pop up a message telling user what is going to happen, and what data is going to leave the client. Otherwise, I am afraid, it is only a matter of time before someone can get in trouble... 

Only now I realized the importance of the detailed disclaimers you put in the code and documentation, but I don't think those disclaimers will be read by the end users. I think the reality is most users don't read documentation.

cc: @pieper @lassoan @jcfr

**Comment by fedorov** [comment]
Here's an idea for the suggested wording for the popup: "By clicking Submit button you acknowledge that you are going to send [whatever it is] over the internet to a remote server. It is your responsibility to ensure that by doing so you are not violating any rules governing access to the data being sent"

**Comment by faustomilletari** [comment]
Yes. Consider it done. I’m doing it right now

**Comment by faustomilletari** [comment]
done.
